[tool.poetry]
name = "admin-panel"
version = "0.1.0"
description = ""
authors = ["lepsick <Lepsick2003@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"




[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
